### ISSUE TITLE
Actions not displayed in "Action Zone"

### ISSUE THREAD

**Issue by ramisedhom** [tot0/ObsidianPPV#6]
Hello Lucas,

This vault is really innovative to implement PPV in Obsidian, really thanks for your effort. I downloaded it and currently trying to use.

I have 1 issue when I create action in "320 🛠 Actions" folder, it doesn't appear in "🚀 Action Zone".

Here is the action file content:
```
---
alias:
- 🛠 Get final list of APIs
tags:
- action
created: 2022-03-09 13:15
projects: [20220309133559]
pillars: [Admin & Team]
---
Priority:: 🟥 1st
Do Date:: 2022-03-09
Done Date:: 
Projects:: [[20220309133559]]
Pillars:: [[💾 Admin & Team|Admin & Team]]
Status:: 🟢 Active
Owner:: 
Next:: 
# 🛠 Get final list of APIs
```
Here is a screenshot of "🚀 Action Zone":
![image](https://user-images.githubusercontent.com/1517228/157441666-085a2c15-abfa-486f-9926-9a2cc5071776.png)

As you can see, action with "Do Date" = today is not displayed. I also tried to change "Do Date" to be tomorrow or yesterday but it's not displayed as well.

Is there something wrong in my action note?

**Comment by ramisedhom** [comment]
I think I fixed by modifying `js/dvActions.js` file, lines 22, 33, 34. I replace `do-date-obj` with `do-date`.

For some reason, `do-date-obj` is "invalid":
```
invalid: Invalid
explanation: "the input "undefined" can't be parsed as ISO 8601"
reason: "unparsable"
```
not sure why!!

I fixed in my fork, will initiate a PR to check from your side.

**Comment by tot0** [comment]
Ahh this explains the change in the linked PR (which I reviewed before looking at this Issue.

I think the exception is happening because the helpers expect the `Do Date::` and `Done Date::` fields to link to a daily note like `[[2022-03-09]]`, they will then look at the links `path` field and parse that as a datetime.
I would recommend linking to the Daily Notes in these fields for some aspects of this implementation to work properly, however if you'd prefer to not link in the Date fields it would make sense to have the `mutateFieldToDate` method in `ObsidianUtils` handle when the `path` field doesn't exist on the field, in this case the date could be passed straight into `luxon.DateTime.fromISO()`.

**Comment by ramisedhom** [comment]
@tot0 You are right, I didn't know those fields should be a link to daily notes. Once I did that Actions appear in "Action Zone". So this PR is useless, you can close it.
